<?php

/**
 * Implementation of hook_menu().
 */
function services_definition_menu() {
  $base = array(
    'access arguments' => array('administer services'),
  );
  $items['admin/config/services/services/%services_endpoint/definition'] = array(
    'title'          => 'Definition',
    'page callback'  => 'services_definition_endpoint',
    'page arguments' => array(4),
    'type'           => MENU_LOCAL_TASK,
  ) + $base;
  $items['admin/config/services/services/%services_endpoint/definition/%/%'] = array(
    'title'          => 'Definition',
    'page callback'  => 'services_definition_define',
    'page arguments' => array(4, 6, 7),
    'type'           => MENU_CALLBACK,
  ) + $base;
  return $items;
}

function services_definition_define($endpoint, $resource_name, $method) {
  $resource_definition_function = '_'. $resource_name .'_resource_definition';
  module_load_include('resource_build.inc', 'services');
  _services_core_resources();

  if(function_exists($resource_definition_function)) {
    $resource_definition = $resource_definition_function();
  }
  if(isset($resource_definition[$resource_name][$method])) {
   debug($resource_definition[$resource_name][$method], 1);
  } else if(isset($resource_definition[$resource_name]['actions'][$method])) {
    debug($resource_definition[$resource_name]['actions'][$method], 1);
  }else if(isset($resource_definition[$resource_name]['relationships'][$method])) {
    debug($resource_definition[$resource_name]['actions'][$method], 1);
  }
  return '';
}
function services_definition_endpoint($endpoint) {
  if (!is_object($endpoint)) {
    $endpoint = services_endpoint_load($endpoint);
  }
  if(!count($endpoint->resources)) {
    drupal_set_message('You have no resources enabled', 'error');
    return '';
  } else {
    drupal_set_message('This is only a list of ENABLED resources and methods.');
  }
  foreach($endpoint->resources as $key=>$resource) {
    $row = array();
    $opcell = array();
    if(isset($resource['operations']))
    foreach($resource['operations'] as $opkey=> $op) {
      $opcell[] = array('data' => $opkey, 'resource'=>$key);
    }      
    if(isset($resource['actions']))
    foreach($resource['actions'] as $opkey=> $op) {
      $opcell[] = array('data' => $opkey, 'resource'=> $key);
    }
    if(isset($resource['relationships']))
    foreach($resource['relationships'] as $opkey=> $op) {
      $opcell[] = array('data' => $opkey, 'resource'=> $key);
    }
    $cols[] = $opcell;
  }
  
  foreach($cols as $column) {
    $output = '<ul>';
    foreach($column as $lineitem) {
      $link = 'admin/config/services/services/'. $endpoint->name .'/definition/'.$lineitem['resource'] .'/'. $lineitem['data'];
      $output .= '<li>'.  l($lineitem['data'], $link, array('external' => FALSE)) .'</li>';
    }
    $output .= '</ul>';
    $row[]= array('data'=>array($column[0]['resource'], $output), 'class' =>array('services-definition'));
  } 
  $rows[] = $row;


  $headers = array('resource', 'method');
  $output = theme('table', array('header' => $headers, 'rows' => $row));
  return $output;
}
